name: unflat
favicon: null
layout_spectrum: 0.599283299408853
typography_spectrum: 0.06363568385131657
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.39846232044510543
  lightness: 0.12074623815715313
  saturation: 0.10227244859561324
  rhythmicContrast: 0.8604409371037036
purpose: []
